In [31]:
import numpy as np
'''Numpy comes in 2 form
1. Vector (1D Array)
2. Matrices (2D Array) '''

# converting a list into 1d array

list_01 = [2,4,5,7,6,87]
arr = np.array(list_01)
arr

array([ 2,  4,  5,  7,  6, 87])

In [32]:
# converting a list to 2D array
matric_list = [[1,2,3],[5,4,6],[8,9,7]]
martcs = np.array(matric_list)
martcs

array([[1, 2, 3],
       [5, 4, 6],
       [8, 9, 7]])

In [33]:
# np.arange
''' np.arange function is like a range function of python'''
arra = np.arange(0,10) # for create a array
arr_2 = np.arange(0,22,2) # here 2 is for gap in range  
print((arr_2,arra))

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


In [34]:
# create a matrices of zeros
zeros_matric = np.zeros((5,5)) # martic is created of (0,0) here in this you can change the tupple value to create a matrice according to you.

zeros_matric_01 = np.zeros((5,2)) # first farrgument for row and 2nd for column
print(zeros_matric_01)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
'''as like zeros you can use one'''
zeros_matric = np.ones((5,5))
print(zeros_matric)
 # martic is created of (1,1) here in this you can change the tupple value to create a matrice according to you.

zeros_matric_01 = np.ones((5,2)) # first farrgument for row and 2nd for column
print(zeros_matric_01)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
# linspace
'''linspace will give you a number count. here as like range where we pass third argumnt for gap as like that here 3rd argument is for how much no you want in matrices'''
array_03 = np.linspace(0,50,10)
array_03


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [37]:
# identity Matices 
'''identity Matices is very usefull when you are doing algebra problems'''
identity_martics = np.eye(5)
identity_martics

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# creating matric or array from random
random_1d_array = np.random.rand(1) # here 1 random no. will generate
random_1d_array_01 = np.random.rand(4) # here 4 diffrent no. will generate
print(random_1d_array)
print(random_1d_array_01)

# creating matrices
random_matrices = np.random.rand(5,5) # it will generate (5,5) matrics
print(random_matrices)




[0.15025725]
[0.11633815 0.45129575 0.65074155 0.68837605]
[[0.75430377 0.70616921 0.51434209 0.09855179 0.27911242]
 [0.73968161 0.34536832 0.65574324 0.11321156 0.38742873]
 [0.73052025 0.42627248 0.58826369 0.93696903 0.35109428]
 [0.43693893 0.9614312  0.30158715 0.18299871 0.44897649]
 [0.25385038 0.62185533 0.64135386 0.34140308 0.13702874]]


In [46]:
# randint

random_matrices_int = np.random.randint(0,100) # it will generate a int value randomly from 1 to 100
random_matrices_int_01 = np.random.randint(0,100,10) # it will generate 10 random no from given list
print(random_matrices_int)
print(random_matrices_int_01)

47
[ 0 64  9  5 19 12 81 21 99  2]


In [52]:
# reshape array
''' here in numpy we can reshape our array to matrices and we get error if we use a number out of range to the matrics'''

arr = np.arange(0,25)
print(arr)
reshape_arr = arr.reshape(5,5) # reshape the array to matrices
print(reshape_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [60]:
# find max value of array

arr_001 = np.arange(0,50)
arr_001_max = np.max(arr_001)
print("max value is :", arr_001_max)

# find min value of array

arr_002 = np.arange(0,50)
arr_002_min = np.min(arr_001)
print("min value is :", arr_002_min)


max value is : 49
min value is : 0


In [66]:
#find index of max value

val_01 = np.random.randint(5,150,50)
print(val_01)
higher_value_index = val_01.argmax()
print("index of higher value in list is :", higher_value_index) 
'''so via this you can find highset value of list and his index also.'''

#find index of min value

val_01 = np.random.randint(5,150,50)
print(val_01)
lower_value_index = val_01.argmin()
print("index of lower value in list is :", lower_value_index) 
'''so via this you can find highset value of list and his index also.'''

[ 93 120  88  30  96  89  51 121  71  58  77  28  63  63 133 110 147  10
 138  22 102  70  88  86  52 119 114 141  63  30  99  94  19  28  60   8
  73  92  18 117 139  45 127  51  19 147 111  79  51 134]
index of higher value in list is : 16
[ 71 136  97  98 108 108 141 124  38  78  86 140  15 122  19 131  75  86
   5  12 130 134 126  86 131 107 103 111  45 115 140  29  26 113  63  19
 118  25  44  34  17  65  53  12  15 125 126 110  89  86]
index of lower value in list is : 18


'so via this you can find highset value of list and his index also.'