In [4]:
import numpy as np

arr = np.arange(0,11)
print(arr)

# for addition of array
new_array = arr + arr
print(new_array)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [6]:
# for subtraction of array
new_subtct_array = arr - arr
print(new_subtct_array)

[0 0 0 0 0 0 0 0 0 0 0]


In [7]:
# for multiplication of array
new_subtct_array = arr * arr
print(new_subtct_array)

[  0   1   4   9  16  25  36  49  64  81 100]


In [8]:
# for multiplication of array with any number
new_subtct_array = arr * 50
print(new_subtct_array)

[  0  50 100 150 200 250 300 350 400 450 500]


In [9]:
# for subtaction of array with any number
new_subtct_array = arr - 50
print(new_subtct_array)

[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40]


In [10]:
divide = arr / arr
divide # here it is a error of zerodivision error but in numpy it will return value 'nan' on the place of zero divisible error

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
# for square
square = arr ** 2
print(square)

[  0   1   4   9  16  25  36  49  64  81 100]


In [15]:
# for sqrt - square root
print(arr)
np.sqrt(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [17]:
# for exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])