In [14]:
import numpy as np

'''if you want to find something value via index then we use this process'''
arr_01 = np.random.randint(10,50,15)
print(arr_01)

print("so on index 3 value on list is :",arr_01[3]) # here we can use this to vind corresponding value of index

new_value = arr_01[10] # store a value on the basis of index into new variable
print("so on index 10 value on list is :",new_value)

# More operation on index

specific_range = arr_01[0:12]
print("so specific range on list is :",specific_range) # here we get value of list from 0 index to 12 index

specific_range = arr_01[10:15]
print("so specific range on list is :",specific_range) 


[23 29 43 48 12 24 48 44 37 41 42 42 20 46 30]
so on index 3 value on list is : 48
so on index 10 value on list is : 42
so specific range on list is : [23 29 43 48 12 24 48 44 37 41 42 42]
so specific range on list is : [42 42 20 46 30]


In [18]:
# broadcast in numpy
'''broadcast is very usefull feature of numpy
and it is diffrent from normal list of python for example'''
lst_02 = np.arange(10,30)
print(lst_02)
lst_02[0:5] = 50 #here for every value of lst_02 is going to assign 50 for every value
print(lst_02)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[50 50 50 50 50 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [27]:
# indexing on 2D array or Indexing on matrics
new_matrics = np.array([[5,10,15],[15,20,25],[30,35,40]])
print(new_matrics)

'''how we can extract the element from the matrices'''

first_element = new_matrics[0][0] # in this 1st 0 tends to 1st row and 2nd 0tends for 1st column
print("first element of matics is :", first_element)

fifth_element = new_matrics[1][1]
print("fifth element of matics is :", fifth_element)

'''another way to extract element from matrics'''
seven_element = new_matrics[2,1]
print("seven element of matics is :",seven_element)


[[ 5 10 15]
 [15 20 25]
 [30 35 40]]
first element of matics is : 5
fifth element of matics is : 20
seven element of matics is : 35


In [33]:
# breaking any matrices according to requirement

matrics_002  = np.array([[25,30,40],[15,80,95],[70,25,50]])
print(matrics_002)

print(matrics_002[:2]) # it will print 2 starting row
print(matrics_002[:2,:2])# it will give 2*2 matrics of starting
print(matrics_002[:1][:3]) # first row of matrics

[[25 30 40]
 [15 80 95]
 [70 25 50]]
[[25 30 40]
 [15 80 95]]
[[25 30]
 [15 80]]
[[25 30 40]]


In [36]:
# comarison operator
lst = np.random.randint(0,30,15)
print(lst)

greater_value = lst > 30
print(greater_value)

[20 10  2 20  2 12  0 10  7 11  1  4 11 20 28]
[False False False False False False False False False False False False
 False False False]
